// Generated by gencpp from file imu/WT61_IMU.msg
// DO NOT EDIT!


#ifndef IMU_MESSAGE_WT61_IMU_H
#define IMU_MESSAGE_WT61_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace imu
{
template <class ContainerAllocator>
struct WT61_IMU_
{
  typedef WT61_IMU_<ContainerAllocator> Type;

  WT61_IMU_()
    : Header()
    , angular_velocity()
    , linear_acceleration()
    , angular()  {
    }
  WT61_IMU_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , angular_velocity(_alloc)
    , linear_acceleration(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::imu::WT61_IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu::WT61_IMU_<ContainerAllocator> const> ConstPtr;

}; // struct WT61_IMU_

typedef ::imu::WT61_IMU_<std::allocator<void> > WT61_IMU;

typedef boost::shared_ptr< ::imu::WT61_IMU > WT61_IMUPtr;
typedef boost::shared_ptr< ::imu::WT61_IMU const> WT61_IMUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu::WT61_IMU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu::WT61_IMU_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu::WT61_IMU_<ContainerAllocator1> & lhs, const ::imu::WT61_IMU_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu::WT61_IMU_<ContainerAllocator1> & lhs, const ::imu::WT61_IMU_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::imu::WT61_IMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu::WT61_IMU_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::WT61_IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu::WT61_IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::WT61_IMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu::WT61_IMU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu::WT61_IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f1af74405a72a71606218daaacc3332";
  }

  static const char* value(const ::imu::WT61_IMU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f1af74405a72a71ULL;
  static const uint64_t static_value2 = 0x606218daaacc3332ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu::WT61_IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu/WT61_IMU";
  }

  static const char* value(const ::imu::WT61_IMU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu::WT61_IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"\n"
"geometry_msgs/Vector3 angular\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::imu::WT61_IMU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu::WT61_IMU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.angular_velocity);
      stream.next(m.linear_acceleration);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WT61_IMU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu::WT61_IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu::WT61_IMU_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_MESSAGE_WT61_IMU_H
